In [1]:
import numpy as np

In [2]:
X_train = np.array([[6, 15],
                   [8, 17],
                   [2, 23],
                   [5, 25],
                   [10, 21],
                   [4, 16]])
print(X_train.shape)
print(X_train)

(6, 2)
[[ 6 15]
 [ 8 17]
 [ 2 23]
 [ 5 25]
 [10 21]
 [ 4 16]]


In [3]:
X_val = np.array([[5, 20],
                 [4, 18],
                 [12, 15],
                 [7, 16]])
print(X_val.shape)
print(X_val)

(4, 2)
[[ 5 20]
 [ 4 18]
 [12 15]
 [ 7 16]]


In [4]:
X_test = np.array([[3, 16],
                  [1, 25],
                  [4, 12],
                  [9, 24]])
print(X_test.shape)
print(X_test)

(4, 2)
[[ 3 16]
 [ 1 25]
 [ 4 12]
 [ 9 24]]


In [5]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
Xs_train = scaler.transform(X_train)
Xs_val = scaler.transform(X_val)
Xs_test = scaler.transform(X_test)
print(Xs_train)
print(Xs_val)
print(Xs_test)

[[0.5   0.   ]
 [0.75  0.2  ]
 [0.    0.8  ]
 [0.375 1.   ]
 [1.    0.6  ]
 [0.25  0.1  ]]
[[0.375 0.5  ]
 [0.25  0.3  ]
 [1.25  0.   ]
 [0.625 0.1  ]]
[[ 0.125  0.1  ]
 [-0.125  1.   ]
 [ 0.25  -0.3  ]
 [ 0.875  0.9  ]]


D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [6]:
beta1 = np.array([6, 5.6, -3.2, 2.4])
beta2 = np.array([7, 3.2, -2.2, 1.8])
beta3 = np.array([5, 4.4, -0.2, 0.8])

y1 = np.array([8.1, 12.9, 13.8, 17.6, 18.3])
y2 = np.array([9.5, 9.8, 16.4, 16.4, 18.1])
y3 = np.array([11.8, 11.7, 16.5, 15.2, 17.6])
y_true = np.array([9.8, 12.1, 14.6, 15.7, 19.5])

In [7]:
y1_res = y1 - y_true
sse1 = np.sum(y1_res ** 2)
y2_res = y2 - y_true
sse2 = np.sum(y2_res ** 2)
y3_res = y3 - y_true
sse3 = np.sum(y3_res ** 2)
print("sse1: ", sse1)
print("sse2: ", sse2)
print("sse3: ", sse3)

sse1:  9.22000000000001
sse2:  11.069999999999986
sse3:  11.629999999999995


In [8]:
beta1_squared = np.sum(beta1 ** 2)
beta2_squared = np.sum(beta2 ** 2)
beta3_squared = np.sum(beta3 ** 2)

print("beta1_squared: ",beta1_squared)
print("beta2_squared: ",beta2_squared)
print("beta3_squared: ",beta3_squared)

beta1_squared:  83.36
beta2_squared:  67.32
beta3_squared:  45.04


In [9]:
alpha = 0.5

ridge1 = sse1 + alpha*beta1_squared
ridge2 = sse2 + alpha*beta2_squared
ridge3 = sse3 + alpha*beta3_squared

print("ridge1: ", ridge1)
print("ridge2: ", ridge2)
print("ridge3: ", ridge3)

ridge1:  50.900000000000006
ridge2:  44.72999999999998
ridge3:  34.14999999999999


In [10]:
beta1_abs = np.sum(abs(beta1))
beta2_abs = np.sum(abs(beta2))
beta3_abs = np.sum(abs(beta3))

print("beta1_abs: ", beta1_abs)
print("beta2_abs: ", beta2_abs)
print("beta3_abs: ", beta3_abs)

beta1_abs:  17.2
beta2_abs:  14.2
beta3_abs:  10.4


In [11]:
lasso1 = sse1 + alpha*beta1_abs
lasso2 = sse2 + alpha*beta2_abs
lasso3 = sse3 + alpha*beta3_abs

print("lasso1: ", lasso1)
print("lasso2: ", lasso2)
print("lasso3: ", lasso3)

lasso1:  17.820000000000007
lasso2:  18.169999999999987
lasso3:  16.829999999999995
