In [1]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures, OneHotEncoder

In [2]:
X_num = np.array([[3], [1], [0], [2], [4], [2]])
print(X_num.shape)
print(X_num)

X_cat = ([[2, 'S'], [1, 'F'], [1, 'S'], [1, 'D'], [2, 'D'], [1, 'F']])
print(X_cat)

(6, 1)
[[3]
 [1]
 [0]
 [2]
 [4]
 [2]]
[[2, 'S'], [1, 'F'], [1, 'S'], [1, 'D'], [2, 'D'], [1, 'F']]


In [3]:
poly = PolynomialFeatures(2)
Xp = poly.fit_transform(X_num)
print(Xp)
enc = OneHotEncoder(sparse = False)
Xe = enc.fit_transform(X_cat)
print(Xe)
X_preprocessed = np.hstack((Xp, Xe))

[[ 1.  3.  9.]
 [ 1.  1.  1.]
 [ 1.  0.  0.]
 [ 1.  2.  4.]
 [ 1.  4. 16.]
 [ 1.  2.  4.]]
[[0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0.]
 [0. 1. 1. 0. 0.]
 [1. 0. 0. 1. 0.]]


In [4]:
print(X_preprocessed)

[[ 1.  3.  9.  0.  1.  0.  0.  1.]
 [ 1.  1.  1.  1.  0.  0.  1.  0.]
 [ 1.  0.  0.  1.  0.  0.  0.  1.]
 [ 1.  2.  4.  1.  0.  1.  0.  0.]
 [ 1.  4. 16.  0.  1.  1.  0.  0.]
 [ 1.  2.  4.  1.  0.  0.  1.  0.]]
